Repository cockpit-project/cockpit-files, pull requests merged in 2025-02, with the labels that each got.

#928 packit: Add Fedora 42, drop 40
  packit.yaml
Labels: no-test, release-blocker

#933 packit: Drop copr_build job redundancy, re-disable Fedora 42
  packit.yaml
Labels: no-test

#935 packit: Re-enable Fedora 42
  packit.yaml
Labels: no-test

#880 Support copy&pasting files with administrator privileges
  src/app.tsx
  src/common.ts
  src/dialogs/copyPasteOwnership.tsx
  src/files-card-body.tsx
  src/files-folder-view.tsx
  src/header.tsx
  src/menu.tsx
  src/ownership.tsx
  src/upload-button.tsx
  test/check-application
Labels: release-note

#947 Fix races in TestFiles.testCopyPaste
  test/check-application
Labels: release-blocker

#948 workflows: Move dependabot and reposchutz from Ubuntu 20.04 to 24.04
  .github/workflows/dependabot.yml
  .github/workflows/reposchutz.yml
Labels: no-test, .github-changes

#762 Support Mac specific keybinds
  src/app.tsx
  src/common.ts
  src/dialogs/keyboardShortcutsHelp.tsx
  src/files-card-body.tsx
  test/check-application
Labels: release-note
